### ISSUE TITLE
Make Database ready for translations

### ISSUE THREAD

**Issue by KevinTss** [coach-marketplace/api#21]
# Context

Add better schema to make able the DB to support mutlilanguage

## Example 

Lang
- Id
- ISO
- NameEN

Sports
- Id

SportContent
- Id
- sportID
- Name
- langID

```
// Bad example
Product
- Id
- Name
- Desc
- Price
```
```
// Good example
Product
- Id
- Price

ProductContent
- Id
- Name
- langID
- Desc
```

**Comment by idogrusoz** [comment]
ISOcodes should be supported with 2 and 3 letter long verisons
